Created by smoke tests for the feature 'workspaces', at 2018-12-19T17:36:36Z

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,34 +1,31 @@
-version: 2
+# features/workspaces
+version: 2.1
+
 jobs:
-  build:
+  workspace-test:
     docker:
-      - image:
+      - image: "circleci/clojure:latest"
+    working_directory: /tmp
     steps:
-      - run: echo "hello world"
-version: 2
-jobs:
-  build:
-    docker:
-      - image: circleci/clojure:latest
-    steps:
-      - run: echo "build"
-  test:
-    docker:
-      - image: circleci/clojure:latest
-    steps:
-      - run: exit $(($RANDOM%2))
-  scan:
-    docker:
-      - image: circleci/clojure:latest
-    steps:
-      - run: echo "test"
+      - run: mkdir -p created-workspace
+      - run: echo "Hello" > created-workspace/important-data
+      - persist_to_workspace:
+          root: created-workspace
+          paths:
+            - important-data
+      - attach_workspace:
+          at: /tmp/attached-workspace
+      - run: |
+          ls -l /tmp/attached-workspace
+          if [[ $(cat /tmp/attached-workspace/important-data) == "Hello" ]]; then
+            echo "It worked!"
+          else
+            echo "My important data is missing!"
+            exit 1
+          fi
+
 workflows:
-  version: 2
-  build_and_test:
+  version: 2.1
+  build:
     jobs:
-      - build
-      - test
-  security_scan:
-    jobs:
-      - build
-      - scan
+      - workspace-test
